cadvisor:
  image: google/cadvisor
  name: cadvisorsrv
  command: -storage_driver=influxdb -storage_driver_db=cadvisordb -storage_driver_host=influxsrv:8086
  ports:
    - "8084:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxdbAmbassadorClient:influxsrv
influxdbAmbassadorClient:
  image: ctlc/ambassador
  name: influxdb_ambassador_client
  expose:
    - "8088"
  environment:
     - INFLUXSRV_PORT_8086_TCP=tcp://x.x.x.x:8086
