influxsrv:
  image: tutum/influxdb
  name: influxsrv
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=cadvisordb
cadvisor:
  image: google/cadvisor
  name: cadvisorsrv
  command: -storage_driver=influxdb -storage_driver_db=cadvisordb -storage_driver_host=influxsrv:8086
  ports:
    - "8084:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxsrv:influxsrv
grafana:
  image: grafana/grafana
  name: grafana
  ports:
    - "3003:3000"
  links:
    - influxsrv:influxsrv
  environment:
    - INFLUXDB_HOST=influxsrv
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisordb
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
