cadvisor:
  image: google/cadvisor
  name: cadvisorsrv
  command: -storage_driver=influxdb -storage_driver_db=cadvisordb -storage_driver_host=influxsrv:8088
  ports:
    - "8085:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  links:
    - influxdbAmbassadorClient:influxsrv
influxdbAmbassadorClient:
  image: svendowideit/ambassador
  name: influxdb_ambassador_client
  ports:
    - "8088:8087"
  expose:
    - "8088"